# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8800pro/unzip-files.sh - DO NOT EDIT

PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/huawei/u8800pro/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
#    vendor/huawei/u8800pro/proprietary/libaudio.so:system/lib/libaudio.so \
#    vendor/huawei/u8800pro/proprietary/libaudio.so:obj/lib/libaudio.so \
#    vendor/huawei/u8800pro/proprietary/libaudiopolicy.so:system/lib/libaudiopolicy.so \
#    vendor/huawei/u8800pro/proprietary/libaudiopolicy.so:obj/lib/libaudiopolicy.so \

# EGL
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/u8800pro/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/u8800pro/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/u8800pro/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/u8800pro/proprietary/libgsl.so:system/lib//libgsl.so \
    vendor/huawei/u8800pro/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/huawei/u8800pro/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \


# RIL
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8800pro/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8800pro/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8800pro/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8800pro/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8800pro/proprietary/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8800pro/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8800pro/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8800pro/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8800pro/proprietary/libdll.so:system/lib/libdll.so \
    vendor/huawei/u8800pro/proprietary/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8800pro/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/u8800pro/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/u8800pro/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/u8800pro/proprietary/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8800pro/proprietary/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8800pro/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8800pro/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8800pro/proprietary/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8800pro/proprietary/libauth.so:system/lib/libauth.so \
    vendor/huawei/u8800pro/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/u8800pro/proprietary/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/u8800pro/proprietary/libidl.so:system/lib/libidl.so \
    vendor/huawei/u8800pro/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/u8800pro/proprietary/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/u8800pro/proprietary/libril.so:system/lib/libril.so \
    vendor/huawei/u8800pro/proprietary/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/u8800pro/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init\
    vendor/huawei/u8800pro/proprietary/netmgrd:/system/bin/netmgrd \
    vendor/huawei/u8800pro/proprietary/sensors.default.so:system/lib/hw/sensors.default.so \

# camera
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8800pro/proprietary/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/huawei/u8800pro/proprietary/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/u8800pro/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8800pro/proprietary/libmmipl.so:system/lib/libmmipl.so \

# vendor
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/compassd:/system/bin/compassd \
    vendor/huawei/u8800pro/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/huawei/u8800pro/proprietary/hw_diag_app:/system/bin/hw_diag_app \
    vendor/huawei/u8800pro/proprietary/libhwrpc.so:obj/lib/libhwrpc.so \
    vendor/huawei/u8800pro/proprietary/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/huawei/u8800pro/proprietary/rmt_oeminfo:/system/bin/rmt_oeminfo \
    vendor/huawei/u8800pro/proprietary/oem_rpc_svc:/system/bin/oem_rpc_svc \
    vendor/huawei/u8800pro/proprietary/oeminfo_test:/system/bin/oeminfo_test \
    vendor/huawei/u8800pro/proprietary/load_oemlogo:/system/bin/load_oemlogo \
    vendor/huawei/u8800pro/proprietary/modempre:/system/bin/modempre \
#    vendor/huawei/u8800pro/proprietary/libOmxVenc.so:/system/lib/libOmxVenc.so \

#project menu
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/ProjectMenuAct.apk:/system/app/ProjectMenuAct.apk \
    vendor/huawei/u8800pro/proprietary/libprojectmenu.so:/system/lib/libprojectmenu.so \
    vendor/huawei/u8800pro/proprietary/libicudata.so:/system/lib/libicudata.so \

#bluetooth
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/BCM4329.hcd:/system/etc/bluetooth/BCM4329.hcd \
    vendor/huawei/u8800pro/proprietary/port-bridge:system/bin/port-bridge \
    vendor/huawei/u8800pro/proprietary/brcm_patchram_plus:system/bin/brcm_patchram_plus \

# wifi
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/huawei/u8800pro/proprietary/wl:system/bin/wl \


