# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/c8650/extract-files.sh - DO NOT EDIT

# All the blobs necessary for c8650

PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/c8650/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \


PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/c8650/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/c8650/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/c8650/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/c8650/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/c8650/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/huawei/c8650/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \

PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/c8650/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/huawei/c8650/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/c8650/proprietary/bin/compassd:system/bin/compassd \
    vendor/huawei/c8650/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/c8650/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/c8650/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \
    vendor/huawei/c8650/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/huawei/c8650/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
    vendor/huawei/c8650/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh \
    vendor/huawei/c8650/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/c8650/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/c8650/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/c8650/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/c8650/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/huawei/c8650/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/c8650/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/c8650/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/c8650/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/c8650/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/c8650/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/c8650/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/c8650/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/c8650/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/c8650/proprietary/lib/libbcm_fm_power.so:system/lib/libbcm_fm_power.so \
    vendor/huawei/c8650/proprietary/lib/libfm_hal.so:system/lib/libfm_hal.so \
    vendor/huawei/c8650/proprietary/lib/libfm_volume.so:system/lib/libfm_volume.so \


# Camera
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/huawei/c8650/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/huawei/c8650/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/huawei/c8650/proprietary/lib/libcameraservice.so:obj/lib/libcameraservice.so \
    vendor/huawei/c8650/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/huawei/c8650/proprietary/lib/libcamera_client.so:obj/lib/libcamera_client.so \
    vendor/huawei/c8650/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/c8650/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/huawei/c8650/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/c8650/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/c8650/proprietary/lib/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/huawei/c8650/proprietary/lib/libmm-abl.so:/system/lib/libmm-abl.so

#    vendor/huawei/c8650/proprietary/lib/libcamera.so:system/lib/libcamera.so \
#    vendor/huawei/c8650/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
#    vendor/huawei/c8650/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
#    vendor/huawei/c8650/proprietary/lib/libcameraservice.so:obj/lib/libcameraservice.so \
#    vendor/huawei/c8650/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
#    vendor/huawei/c8650/proprietary/lib/libcamera_client.so:obj/lib/libcamera_client.so \

# OMX
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxWmvDec.so:/system/lib/libOmxWmvDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/huawei/c8650/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so\

# HW
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/c8650/proprietary/lib/hw/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/huawei/c8650/proprietary/lib/hw/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/huawei/c8650/proprietary/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
    vendor/huawei/c8650/proprietary/lib/hw/libbcmfm_if.so:system/lib/hw/libbcmfm_if.so

#    vendor/huawei/c8650/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
#    vendor/huawei/c8650/proprietary/lib/hw/gps.c8650.so:system/lib/hw/gps.c8650.so \

# vendor
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/c8650/proprietary/bin/vold:system/bin/vold \
    vendor/huawei/c8650/proprietary/bin/modempre:system/bin/modempre \
    vendor/huawei/c8650/proprietary/lib/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/huawei/c8650/proprietary/lib/libcommondefs.so:/system/lib/libcommondefs.so \
    vendor/huawei/c8650/proprietary/lib/libmmprocess.so:system/lib/libmmprocess.so\
    vendor/huawei/c8650/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/c8650/proprietary/lib/libhwrpc.so:obj/lib/libhwrpc.so \

# removed by ioz9 for fix gps bug
#    vendor/huawei/c8650/proprietary/lib/libloc_api-rpc-qc.so:/system/lib/libloc_api-rpc-qc.so \

# wifi
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/huawei/c8650/proprietary/bin/wl:system/bin/wl \

# bluetooth
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/huawei/c8650/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/c8650/proprietary/etc/bluetooth/BCM4329.hcd:system/etc/bluetooth/BCM4329.hcd \
    vendor/huawei/c8650/proprietary/etc/bluetooth/init.bcm.bt.sh:system/etc/bluetooth/init.bcm.bt.sh \
    vendor/huawei/c8650/proprietary/etc/bluetooth/init.bcm.chip_off.sh:system/etc/bluetooth/init.bcm.chip_off.sh \
    vendor/huawei/c8650/proprietary/etc/bluetooth/init.bcm.chip_on.sh:system/etc/bluetooth/init.bcm.chip_on.sh

# ril
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/libreference-ril.so:/system/lib/libreference-ril.so \
    vendor/huawei/c8650/proprietary/lib/libril.so:/system/lib/libril.so


# hci
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/bin/hci_dev_state:system/bin/hci_dev_state \
    vendor/huawei/c8650/proprietary/bin/hciattach:system/bin/hciattach

# added by ioz9 for fix video camera, it edit in StagefrightRecoder EBUSY
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/libmediaplayerservice.so:/system/lib/libmediaplayerservice.so
    
# added by ioz9 for fix camera audio
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/media/audio/ui/camera_click.ogg:/system/media/audio/ui/camera_click.ogg

# added by ioz9 for C+W
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/bin/dhcpcd:system/xbin/dhcpcd \
    vendor/huawei/c8650/proprietary/xbin/cfgctnet:system/xbin/cfgctnet \
    vendor/huawei/c8650/proprietary/xbin/cfgctwap:system/xbin/cfgctwap \
    vendor/huawei/c8650/proprietary/xbin/cplusw:system/xbin/cplusw \
    vendor/huawei/c8650/proprietary/lib/libcplusw.so:/system/lib/libcplusw.so \
    vendor/huawei/c8650/proprietary/lib/libcpwjni.so:/system/lib/libcpwjni.so \
    vendor/huawei/c8650/proprietary/lib/libc+wsip.so:/system/lib/libc+wsip.so \
    vendor/huawei/c8650/proprietary/app/cpwservice.apk:/system/app/cpwservice.apk

# added by ioz9 for soundfx
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/soundfx/libbundlewrapper.so:/system/lib/soundfx/libbundlewrapper.so

# added by ioz9 for opencore
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/libopencore_author.so:/system/lib/libopencore_author.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_common.so:/system/lib/libopencore_common.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_download.so:/system/lib/libopencore_download.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_downloadreg.so:/system/lib/libopencore_downloadreg.so \
    vendor/huawei/c8650/proprietary/lib/libopencorehw.so:/system/lib/libopencorehw.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_mp4local.so:/system/lib/libopencore_mp4local.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_mp4localreg.so:/system/lib/libopencore_mp4localreg.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_net_support.so:/system/lib/libopencore_net_support.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_player.so:/system/lib/libopencore_player.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_rtsp.so:/system/lib/libopencore_rtsp.so \
    vendor/huawei/c8650/proprietary/lib/libopencore_rtspreg.so:/system/lib/libopencore_rtspreg.so \
    vendor/huawei/c8650/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so

# added by ioz9 for menu
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/app/ProjectMenuAct.apk:/system/app/ProjectMenuAct.apk \
    vendor/huawei/c8650/proprietary/lib/libprojectmenu.so:/system/lib/libprojectmenu.so

# added by ioz9 for audioeq
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/huawei/c8650/proprietary/lib/libaudioeq.so:/system/lib/libaudioeq.so

# added by ioz9 for fix LED Bug
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/hw/lights.c8650.so:system/lib/hw/lights.c8650.so
