# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8800x/unzip-files.sh - DO NOT EDIT

#bluez-plugin
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/bluez-plugin/audio.so:system/lib/bluez-plugin/audio.so \
    vendor/huawei/u8800x/proprietary/bluez-plugin/input.so:system/lib/bluez-plugin/input.so \

# EGL
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/u8800x/proprietary/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/u8800x/proprietary/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/u8800x/proprietary/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/u8800x/proprietary/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \

#project menu
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/ProjectMenuAct.apk:/system/app/ProjectMenuAct.apk \
    vendor/huawei/u8800x/proprietary/libprojectmenu.so:/system/lib/libprojectmenu.so \
    vendor/huawei/u8800x/proprietary/libicudata.so:/system/lib/libicudata.so \

#hw
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
    vendor/huawei/u8800x/proprietary/hw/gps.u8800.so:system/lib/hw/gps.u8800.so \
    vendor/huawei/u8800x/proprietary/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/huawei/u8800x/proprietary/hw/overlay.default.so:system/lib/hw/overlay.default.so \
    vendor/huawei/u8800x/proprietary/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/u8800x/proprietary/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \

#modules
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/modules/libra.ko:system/lib/modules/libra.ko \
    vendor/huawei/u8800x/proprietary/modules/libra_ftm.ko:system/lib/modules/libra_ftm.ko \
    vendor/huawei/u8800x/proprietary/modules/librasdioif.ko:system/lib/modules/librasdioif.ko \

#soundfx
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/soundfx/libcyanogen-dsp.so:system/lib/soundfx/libcyanogen-dsp.so \
    vendor/huawei/u8800x/proprietary/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/huawei/u8800x/proprietary/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \

#bin
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/huawei/u8800x/proprietary/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8800x/proprietary/rild:system/bin/rild \
    vendor/huawei/u8800x/proprietary/btwlancoex:system/bin/btwlancoex \
    vendor/huawei/u8800x/proprietary/compassd:system/bin/compassd \
    vendor/huawei/u8800x/proprietary/dexopt-wrapper:system/bin/dexopt-wrapper \
    vendor/huawei/u8800x/proprietary/hciattach:system/bin/hciattach \
    vendor/huawei/u8800x/proprietary/hostapd:system/bin/hostapd \
    vendor/huawei/u8800x/proprietary/hostapd_cli:system/bin/hostapd_cli \
    vendor/huawei/u8800x/proprietary/hw_diag_app:system/bin/hw_diag_app \
    vendor/huawei/u8800x/proprietary/load_oemlogo:system/bin/load_oemlogo \
    vendor/huawei/u8800x/proprietary/modempre:system/bin/modempre \
    vendor/huawei/u8800x/proprietary/netd:system/bin/netd \
    vendor/huawei/u8800x/proprietary/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/u8800x/proprietary/oeminfo_test:system/bin/oeminfo_test \
    vendor/huawei/u8800x/proprietary/port-bridge:system/bin/port-bridge \
    vendor/huawei/u8800x/proprietary/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/u8800x/proprietary/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/u8800x/proprietary/vold:system/bin/vold

#sh
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/modelid_cfg.sh:system/bin/modelid_cfg.sh \

#f4w
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/huawei/u8800x/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \

# other
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/invoke_mock_media_player.so:system/lib/invoke_mock_media_player.so \
    vendor/huawei/u8800x/proprietary/liba2dp.so:system/lib/liba2dp.so \
    vendor/huawei/u8800x/proprietary/libacc.so:system/lib/libacc.so \
    vendor/huawei/u8800x/proprietary/libandroid.so:system/lib/libandroid.so \
    vendor/huawei/u8800x/proprietary/libandroid_servers.so:system/lib/libandroid_servers.so \
    vendor/huawei/u8800x/proprietary/libandroidterm2.so:system/lib/libandroidterm2.so \
    vendor/huawei/u8800x/proprietary/libaudio.so:system/lib/libaudio.so \
    vendor/huawei/u8800x/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/huawei/u8800x/proprietary/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
    vendor/huawei/u8800x/proprietary/libaudioflinger.so:system/lib/libaudioflinger.so \
    vendor/huawei/u8800x/proprietary/libaudiopolicy.so:system/lib/libaudiopolicy.so \
    vendor/huawei/u8800x/proprietary/libauth.so:system/lib/libauth.so \
    vendor/huawei/u8800x/proprietary/libbinder.so:system/lib/libbinder.so \
    vendor/huawei/u8800x/proprietary/libbluedroid.so:system/lib/libbluedroid.so \
    vendor/huawei/u8800x/proprietary/libbluetooth.so:system/lib/libbluetooth.so \
    vendor/huawei/u8800x/proprietary/libbluetoothd.so:system/lib/libbluetoothd.so \
    vendor/huawei/u8800x/proprietary/libc.so:system/lib/libc.so \
    vendor/huawei/u8800x/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/huawei/u8800x/proprietary/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/huawei/u8800x/proprietary/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/huawei/u8800x/proprietary/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8800x/proprietary/libc_malloc_debug_leak.so:system/lib/libc_malloc_debug_leak.so \
    vendor/huawei/u8800x/proprietary/libc_malloc_debug_qemu.so:system/lib/libc_malloc_debug_qemu.so \
    vendor/huawei/u8800x/proprietary/libcrypto.so:system/lib/libcrypto.so \
    vendor/huawei/u8800x/proprietary/libctest.so:system/lib/libctest.so \
    vendor/huawei/u8800x/proprietary/libcutils.so:system/lib/libcutils.so \
    vendor/huawei/u8800x/proprietary/libdbus.so:system/lib/libdbus.so \
    vendor/huawei/u8800x/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8800x/proprietary/libdiskconfig.so:system/lib/libdiskconfig.so \
    vendor/huawei/u8800x/proprietary/libdl.so:system/lib/libdl.so \
    vendor/huawei/u8800x/proprietary/libdll.so:system/lib/libdll.so \
    vendor/huawei/u8800x/proprietary/libdrm1.so:system/lib/libdrm1.so \
    vendor/huawei/u8800x/proprietary/libdrm1_jni.so:system/lib/libdrm1_jni.so \
    vendor/huawei/u8800x/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8800x/proprietary/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8800x/proprietary/libdvm.so:system/lib/libdvm.so \
    vendor/huawei/u8800x/proprietary/libeffects.so:system/lib/libeffects.so \
    vendor/huawei/u8800x/proprietary/libEGL.so:system/lib/libEGL.so \
    vendor/huawei/u8800x/proprietary/libemoji.so:system/lib/libemoji.so \
    vendor/huawei/u8800x/proprietary/libETC1.so:system/lib/libETC1.so \
    vendor/huawei/u8800x/proprietary/libexif.so:system/lib/libexif.so \
    vendor/huawei/u8800x/proprietary/libexpat.so:system/lib/libexpat.so \
    vendor/huawei/u8800x/proprietary/libext2_blkid.so:system/lib/libext2_blkid.so \
    vendor/huawei/u8800x/proprietary/libext2_com_err.so:system/lib/libext2_com_err.so \
    vendor/huawei/u8800x/proprietary/libext2_e2p.so:system/lib/libext2_e2p.so \
    vendor/huawei/u8800x/proprietary/libext2fs.so:system/lib/libext2fs.so \
    vendor/huawei/u8800x/proprietary/libext2_profile.so:system/lib/libext2_profile.so \
    vendor/huawei/u8800x/proprietary/libext2_uuid.so:system/lib/libext2_uuid.so \
    vendor/huawei/u8800x/proprietary/libFFTEm.so:system/lib/libFFTEm.so \
    vendor/huawei/u8800x/proprietary/libFLAC.so:system/lib/libFLAC.so \
    vendor/huawei/u8800x/proprietary/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/u8800x/proprietary/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/huawei/u8800x/proprietary/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/huawei/u8800x/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/u8800x/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/u8800x/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/u8800x/proprietary/libgui.so:system/lib/libgui.so \
    vendor/huawei/u8800x/proprietary/libhardware.so:system/lib/libhardware.so \
    vendor/huawei/u8800x/proprietary/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/huawei/u8800x/proprietary/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8800x/proprietary/libhwrpc.so:obj/lib/libhwrpc.so \
    vendor/huawei/u8800x/proprietary/libicui18n.so:system/lib/libicui18n.so \
    vendor/huawei/u8800x/proprietary/libicuuc.so:system/lib/libicuuc.so \
    vendor/huawei/u8800x/proprietary/libiprouteutil.so:system/lib/libiprouteutil.so \
    vendor/huawei/u8800x/proprietary/libjnigraphics.so:system/lib/libjnigraphics.so \
    vendor/huawei/u8800x/proprietary/libjni_pinyinime.so:system/lib/libjni_pinyinime.so \
    vendor/huawei/u8800x/proprietary/libjpeg.so:system/lib/libjpeg.so \
    vendor/huawei/u8800x/proprietary/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/u8800x/proprietary/liblog.so:system/lib/liblog.so \
    vendor/huawei/u8800x/proprietary/liblzo.so:system/lib/liblzo.so \
    vendor/huawei/u8800x/proprietary/libm.so:system/lib/libm.so \
    vendor/huawei/u8800x/proprietary/libmedia.so:system/lib/libmedia.so \
    vendor/huawei/u8800x/proprietary/libmedia_jni.so:system/lib/libmedia_jni.so \
    vendor/huawei/u8800x/proprietary/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
    vendor/huawei/u8800x/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/huawei/u8800x/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/u8800x/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/u8800x/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8800x/proprietary/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/huawei/u8800x/proprietary/libnativehelper.so:system/lib/libnativehelper.so \
    vendor/huawei/u8800x/proprietary/libncurses.so:system/lib/libncurses.so \
    vendor/huawei/u8800x/proprietary/libnetlink.so:system/lib/libnetlink.so \
    vendor/huawei/u8800x/proprietary/libnetutils.so:system/lib/libnetutils.so \
    vendor/huawei/u8800x/proprietary/libnfc_ndef.so:system/lib/libnfc_ndef.so \
    vendor/huawei/u8800x/proprietary/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8800x/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8800x/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/u8800x/proprietary/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/huawei/u8800x/proprietary/libOmxVdec.so:system/lib/libOmxVdec.so \
    vendor/huawei/u8800x/proprietary/libOmxVenc.so:system/lib/libOmxVenc.so \
    vendor/huawei/u8800x/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8800x/proprietary/libOpenSLES.so:system/lib/libOpenSLES.so \
    vendor/huawei/u8800x/proprietary/liboverlay.so:system/lib/liboverlay.so \
    vendor/huawei/u8800x/proprietary/libpagemap.so:system/lib/libpagemap.so \
    vendor/huawei/u8800x/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8800x/proprietary/libphoneloc-jni.so:system/lib/libphoneloc-jni.so \
    vendor/huawei/u8800x/proprietary/libpixelflinger.so:system/lib/libpixelflinger.so \
    vendor/huawei/u8800x/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8800x/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8800x/proprietary/libril.so:system/lib/libril.so \
    vendor/huawei/u8800x/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8800x/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8800x/proprietary/librpc.so:system/lib/librpc.so \
    vendor/huawei/u8800x/proprietary/libRS.so:system/lib/libRS.so \
    vendor/huawei/u8800x/proprietary/librs_jni.so:system/lib/librs_jni.so \
    vendor/huawei/u8800x/proprietary/librtp_jni.so:system/lib/librtp_jni.so \
    vendor/huawei/u8800x/proprietary/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/huawei/u8800x/proprietary/libskiagl.so:system/lib/libskiagl.so \
    vendor/huawei/u8800x/proprietary/libsonivox.so:system/lib/libsonivox.so \
    vendor/huawei/u8800x/proprietary/libsoundpool.so:system/lib/libsoundpool.so \
    vendor/huawei/u8800x/proprietary/libsqlite.so:system/lib/libsqlite.so \
    vendor/huawei/u8800x/proprietary/libsqlite_jni.so:system/lib/libsqlite_jni.so \
    vendor/huawei/u8800x/proprietary/libSR_AudioIn.so:system/lib/libSR_AudioIn.so \
    vendor/huawei/u8800x/proprietary/libsrec_jni.so:system/lib/libsrec_jni.so \
    vendor/huawei/u8800x/proprietary/libssl.so:system/lib/libssl.so \
    vendor/huawei/u8800x/proprietary/libstagefright.so:system/lib/libstagefright.so \
    vendor/huawei/u8800x/proprietary/libstagefright_amrnb_common.so:system/lib/libstagefright_amrnb_common.so \
    vendor/huawei/u8800x/proprietary/libstagefright_avc_common.so:system/lib/libstagefright_avc_common.so \
    vendor/huawei/u8800x/proprietary/libstagefright_color_conversion.so:system/lib/libstagefright_color_conversion.so \
    vendor/huawei/u8800x/proprietary/libstagefright_enc_common.so:system/lib/libstagefright_enc_common.so \
    vendor/huawei/u8800x/proprietary/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
    vendor/huawei/u8800x/proprietary/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/huawei/u8800x/proprietary/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/huawei/u8800x/proprietary/libstdc++.so:system/lib/libstdc++.so \
    vendor/huawei/u8800x/proprietary/libstlport.so:system/lib/libstlport.so \
    vendor/huawei/u8800x/proprietary/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
    vendor/huawei/u8800x/proprietary/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so \
    vendor/huawei/u8800x/proprietary/libsystem_server.so:system/lib/libsystem_server.so \
    vendor/huawei/u8800x/proprietary/libsysutils.so:system/lib/libsysutils.so \
    vendor/huawei/u8800x/proprietary/libterm.so:system/lib/libterm.so \
    vendor/huawei/u8800x/proprietary/libthread_db.so:system/lib/libthread_db.so \
    vendor/huawei/u8800x/proprietary/libttspico.so:system/lib/libttspico.so \
    vendor/huawei/u8800x/proprietary/libttssynthproxy.so:system/lib/libttssynthproxy.so \
    vendor/huawei/u8800x/proprietary/libui.so:system/lib/libui.so \
    vendor/huawei/u8800x/proprietary/libutils.so:system/lib/libutils.so \
    vendor/huawei/u8800x/proprietary/libvorbisidec.so:system/lib/libvorbisidec.so \
    vendor/huawei/u8800x/proprietary/libwebcore.so:system/lib/libwebcore.so \
    vendor/huawei/u8800x/proprietary/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8800x/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8800x/proprietary/libwpa_client.so:system/lib/libwpa_client.so \
    vendor/huawei/u8800x/proprietary/libz.so:system/lib/libz.so \
    # Woody Guo @ 2012/05/29
    # Remove libskia.so so changing font would work
    # vendor/huawei/u8800x/proprietary/libskia.so:system/lib/libskia.so \

# append from geno by zhangzhi 20120216
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/u8800x/proprietary/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/u8800x/proprietary/libidl.so:system/lib/libidl.so \
    vendor/huawei/u8800x/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/u8800x/proprietary/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/u8800x/proprietary/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/u8800x/proprietary/netmgrd:system/bin/netmgrd \

# append lib/egl from geno by zhangzhi 20120216
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/egl/libEGL_adreno200.so:system/lib/libEGL_adreno200.so \
    vendor/huawei/u8800x/proprietary/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/u8800x/proprietary/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/u8800x/proprietary/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \

# append lib/hw from geno by zhangzhi 20120216
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/huawei/u8800x/proprietary/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/huawei/u8800x/proprietary/hw/overlay.default.so:system/lib/hw/overlay.default.so \
    vendor/huawei/u8800x/proprietary/hw/sensors.default.so:system/lib/hw/sensors.default.so \

# append lib/modules from geno by zhangzhi 20120216
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/modules/libra_ftm.ko:system/lib/modules/libra_ftm.ko \
    vendor/huawei/u8800x/proprietary/modules/libra.ko:system/lib/modules/libra.ko \
    vendor/huawei/u8800x/proprietary/modules/librasdioif.ko:system/lib/modules/librasdioif.ko

# append NetworkLocation.apk for gps locate right.
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800x/proprietary/NetworkLocation.apk:/system/app/NetworkLocation.apk \

