# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8800/unzip-files.sh - DO NOT EDIT

#bluez-plugin
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/bluez-plugin/audio.so:system/lib/bluez-plugin/audio.so \
    vendor/huawei/u8800/proprietary/bluez-plugin/input.so:system/lib/bluez-plugin/input.so \

# EGL
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/u8800/proprietary/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/u8800/proprietary/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/u8800/proprietary/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/u8800/proprietary/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \

#project menu
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/ProjectMenuAct.apk:/system/app/ProjectMenuAct.apk \
    vendor/huawei/u8800pro/proprietary/libprojectmenu.so:/system/lib/libprojectmenu.so \
    vendor/huawei/u8800pro/proprietary/libicudata.so:/system/lib/libicudata.so \

#hw
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
    vendor/huawei/u8800/proprietary/hw/gps.u8800.so:system/lib/hw/gps.u8800.so \
    vendor/huawei/u8800/proprietary/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/huawei/u8800/proprietary/hw/gralloc.msm7x30.so:system/lib/hw/gralloc.msm7x30.so \
    vendor/huawei/u8800/proprietary/hw/lights.u8800.so:system/lib/hw/lights.u8800.so \
    vendor/huawei/u8800/proprietary/hw/overlay.default.so:system/lib/hw/overlay.default.so \
    vendor/huawei/u8800/proprietary/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/u8800/proprietary/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \

#modules
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/modules/libra.ko:system/lib/modules/libra.ko \
    vendor/huawei/u8800/proprietary/modules/libra_ftm.ko:system/lib/modules/libra_ftm.ko \
    vendor/huawei/u8800/proprietary/modules/librasdioif.ko:system/lib/modules/librasdioif.ko \

#soundfx
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/soundfx/libcyanogen-dsp.so:system/lib/soundfx/libcyanogen-dsp.so \
    vendor/huawei/u8800/proprietary/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/huawei/u8800/proprietary/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \

#bin
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/huawei/u8800/proprietary/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8800/proprietary/rild:system/bin/rild \
    vendor/huawei/u8800/proprietary/btwlancoex:system/bin/btwlancoex \
    vendor/huawei/u8800/proprietary/compassd:system/bin/compassd \
    vendor/huawei/u8800/proprietary/dexopt-wrapper:system/bin/dexopt-wrapper \
    vendor/huawei/u8800/proprietary/hciattach:system/bin/hciattach \
    vendor/huawei/u8800/proprietary/hostapd:system/bin/hostapd \
    vendor/huawei/u8800/proprietary/hostapd_cli:system/bin/hostapd_cli \
    vendor/huawei/u8800/proprietary/hw_diag_app:system/bin/hw_diag_app \
    vendor/huawei/u8800/proprietary/load_oemlogo:system/bin/load_oemlogo \
    vendor/huawei/u8800/proprietary/modempre:system/bin/modempre \
    vendor/huawei/u8800/proprietary/netd:system/bin/netd \
    vendor/huawei/u8800/proprietary/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/u8800/proprietary/oeminfo_test:system/bin/oeminfo_test \
    vendor/huawei/u8800/proprietary/port-bridge:system/bin/port-bridge \
    vendor/huawei/u8800/proprietary/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/u8800/proprietary/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/u8800/proprietary/vold:system/bin/vold

#sh
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/modelid_cfg.sh:system/bin/modelid_cfg.sh \

#f4w
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/huawei/u8800/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \

# other
PRODUCT_COPY_FILES += \
    vendor/huawei/u8800/proprietary/invoke_mock_media_player.so:system/lib/invoke_mock_media_player.so \
    vendor/huawei/u8800/proprietary/libandroidterm2.so:system/lib/libandroidterm2.so \
    vendor/huawei/u8800/proprietary/libaudio.so:system/lib/libaudio.so \
    vendor/huawei/u8800/proprietary/libauth.so:system/lib/libauth.so \
    vendor/huawei/u8800/proprietary/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8800/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8800/proprietary/libdll.so:system/lib/libdll.so \
    vendor/huawei/u8800/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8800/proprietary/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8800/proprietary/libdvm.so:system/lib/libdvm.so \
    vendor/huawei/u8800/proprietary/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/u8800/proprietary/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/huawei/u8800/proprietary/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/huawei/u8800/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/u8800/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/u8800/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/u8800/proprietary/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/huawei/u8800/proprietary/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8800/proprietary/libhwrpc.so:obj/lib/libhwrpc.so \
    vendor/huawei/u8800/proprietary/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/u8800/proprietary/libm.so:system/lib/libm.so \
    vendor/huawei/u8800/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/huawei/u8800/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/u8800/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/u8800/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8800/proprietary/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/huawei/u8800/proprietary/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8800/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8800/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/u8800/proprietary/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/huawei/u8800/proprietary/libOmxVdec.so:system/lib/libOmxVdec.so \
    vendor/huawei/u8800/proprietary/libOmxVenc.so:system/lib/libOmxVenc.so \
    vendor/huawei/u8800/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8800/proprietary/liboverlay.so:system/lib/liboverlay.so \
    vendor/huawei/u8800/proprietary/libpagemap.so:system/lib/libpagemap.so \
    vendor/huawei/u8800/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8800/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8800/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8800/proprietary/libril.so:system/lib/libril.so \
    vendor/huawei/u8800/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8800/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8800/proprietary/librpc.so:system/lib/librpc.so \
    vendor/huawei/u8800/proprietary/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/huawei/u8800/proprietary/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8800/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8800/proprietary/libz.so:system/lib/libz.so \


